---
# Template configuration files for windows-packages

- name: Set SELinux booleans
  seboolean:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    persistent: "{{ item.persistent | default('false') }}"
  loop: "{{ windows-packages_selinux_booleans }}"
  when:
    - ansible_selinux.status == "enabled"
    - windows-packages_enable_selinux
  become: true
